version: "3"
services:
  nginx:
    build: ${HOMEDIR}/docker
    image: zongzw/nginx-test-ngx_modules:latest
    # image: nginx:latest
    container_name: USENGX
    ports:
     - 10082:80
    volumes:
     - ${HOMEDIR}/conf.d/nginx.conf:/etc/nginx/nginx.conf
     - ${HOMEDIR}/conf.d/js-modules:/etc/nginx/js-modules
     - ${HOMEDIR}/src:/root/src
     - ${HOMEDIR}/modules/ngx_http_echo_module.so:/etc/nginx/modules/ngx_http_echo_module.so
     - ${HOMEDIR}/modules/ngx_http_eval_module.so:/etc/nginx/modules/ngx_http_eval_module.so


