version: "3"
services:
  nginx:
    build: ${HOMEDIR}/docker
    image: zongzw/nginx-devel-ngx_modules:latest
    privileged: true
    # image: nginx:latest
    container_name: DEVNGX
    ports:
     - 10081:80
    volumes:
     - ${HOMEDIR}:/var/workspace
    working_dir: /var/workspace
    entrypoint: "bash /root/daemon.sh"
