version: "3"
services:
  nginx:
    build: ./docker
    image: zongzw/nginx-devel-ngx_modules:latest
    # image: nginx:latest
    container_name: DEVNGX
    ports:
     - 10081:80
    volumes:
     - ${HOMEDIR}/conf.d/nginx.conf:/etc/nginx/nginx.conf
     - ${HOMEDIR}/modules:/root/modules

